version: "2"

formatters:
  enable:
    - gofumpt
    - golines
    - gci

linters:
  enable:
    - errcheck # Errcheck is a program for checking for unchecked errors in Go code. These unchecked errors can be critical bugs in some cases.
    - govet # Vet examines Go source code and reports suspicious constructs. It is roughly the same as 'go vet' and uses its passes. [auto-fix]
    - ineffassign # Detects when assignments to existing variables are not used. [fast]
    - staticcheck # It's the set of rules from staticcheck. [auto-fix]
    - unused # Checks Go code for unused constants, variables, functions and types.

    - asciicheck # Checks that all code identifiers does not have non-ASCII symbols in the name. [fast]
    - bidichk # Checks for dangerous unicode character sequences. [fast]
    - copyloopvar # A linter detects places where loop variables are copied. [fast, auto-fix]
    - decorder # Check declaration order and count of types, constants, variables and functions. [fast]
    - dupl # Detects duplicate fragments of code. [fast]
    - embeddedstructfieldcheck # Embedded types should be at the top of the field list of a struct, and there must be an empty line separating embedded fields from regular fields. [fast]
    - funcorder # Checks the order of functions, methods, and constructors. [fast]
    - funlen # Checks for long functions. [fast]
    - gocognit # Computes and checks the cognitive complexity of functions. [fast]
    - godoclint # Checks Golang's documentation practice (godoc). [fast]
    - godot # Check if comments end in a period. [fast, auto-fix]
    - godox # Detects usage of FIXME, TODO and other keywords inside comments. [fast]
    - gomoddirectives # Manage the use of 'replace', 'retract', and 'excludes' directives in go.mod. [fast]
    - interfacebloat # A linter that checks the number of methods inside an interface. [fast]
    - iotamixing # Checks if iotas are being used in const blocks with other non-iota declarations. [fast]
    - lll # Reports long lines. [fast]
    - misspell # Finds commonly misspelled English words. [fast, auto-fix]
    - mnd # An analyzer to detect magic numbers. [fast]
    - nosprintfhostport # Checks for misuse of Sprintf to construct a host with port in a URL. [fast]
    - predeclared # Find code that shadows one of Go's predeclared identifiers. [fast]
    - revive # Fast, configurable, extensible, flexible, and beautiful linter for Go. Drop-in replacement of golint. [auto-fix]
    - testableexamples # Linter checks if examples are testable (have an expected output). [fast]
    - testpackage # Linter that makes you use a separate _test package. [fast]
    - unqueryvet # Detects SELECT * in SQL queries and SQL builders, preventing performance issues and encouraging explicit column selection. [fast]
    - usestdlibvars # A linter that detect the possibility to use variables/constants from the Go standard library. [fast, auto-fix]
    - whitespace # Whitespace is a linter that checks for unnecessary newlines at the start and end of functions, if, for, etc. [fast, auto-fix]

    - bodyclose # Checks whether HTTP response body is closed successfully.
    - errname # Checks that sentinel errors are prefixed with the `Err` and error types are suffixed with the `Error`.
    - errorlint # Find code that can cause problems with the error wrapping scheme introduced in Go 1.13. [auto-fix]
    - exhaustive # Check exhaustiveness of enum switch statements.
    - exhaustruct # Checks if all structure fields are initialized.
    - fatcontext # Detects nested contexts in loops and function literals. [auto-fix]
    - forbidigo # Forbids identifiers.
    - gochecknoglobals # Check that no global variables exist.
    - goconst # Finds repeated strings that could be replaced by a constant.
    - gocritic # Provides diagnostics that check for bugs, performance and style issues. [auto-fix]
    - gosec # Inspects source code for security problems.
    - iface # Detect the incorrect use of interfaces, helping developers avoid interface pollution. [auto-fix]
    - intrange # Intrange is a linter to find places where for loops could make use of an integer range. [auto-fix]
    - ireturn # Accept Interfaces, Return Concrete Types.
    - makezero # Find slice declarations with non-zero initial length.
    - mirror # Reports wrong mirror patterns of bytes/strings usage. [auto-fix]
    - modernize # A suite of analyzers that suggest simplifications to Go code, using modern language and library features.
    - musttag # Enforce field tags in (un)marshaled structs.
    - nilerr # Find the code that returns nil even if it checks that the error is not nil.
    - nilnesserr # Reports constructs that checks for err != nil, but returns a different nil value error.
    - nilnil # Checks that there is no simultaneous return of `nil` error and an invalid value.
    - noctx # Detects function and method with missing usage of context.Context.
    - noinlineerr # Disallows inline error handling (`if err := ...; err != nil {`).
    - nonamedreturns # Reports all named returns.
    - reassign # Checks that package variables are not reassigned.
    - recvcheck # Checks for receiver type consistency.
    - rowserrcheck # Checks whether Rows.Err of rows is checked successfully.
    - sloglint # Ensure consistent code style when using log/slog. [auto-fix]
    - sqlclosecheck # Checks that sql.Rows, sql.Stmt, sqlx.NamedStmt, pgx.Query are closed.
    - tparallel # Tparallel detects inappropriate usage of t.Parallel() method in your Go test codes.
    - unconvert # Remove unnecessary type conversions.
    - unparam # Reports unused function parameters.
